---

- name: Install package dependencies
  apt: name={{item}} state=installed
  with_items:
    - git
    - build-essential
    - autogen
    - automake
    - base-files
    - base-passwd
    - bash
    - coreutils
    - dash
    - debianutils
    - diffutils
    - dpkg
    - e2fsprogs
    - findutils
    - grep
    - gzip
    - hostname
    - ncurses-base
    - libevent-dev
    - ncurses-bin
    - perl-base
    - sed
    - login
    - sysvinit-utils
    - sysvinit
    - tar
    - bsdutils
    - mount
    - util-linux
    - libc6-dev
    - libc-dev
    - gcc
    - g++
    - make
    - dpkg-dev
    - autotools-dev
    - debhelper
    - dh-autoreconf
    - dpatch
    - libclamav-dev
    - libpcre3-dev
    - zlib1g-dev
    - pkg-config
    - libssl-dev
    - libssl1.0.0
    - adduser
    - perl
    - libc6
    - libgcc1
    - libpcre3
    - libtommath0
    - zlib1g
    - clamav
    - clamav-freshclam

- name: check out e2guardian
  git:
    repo: 'https://github.com/e2guardian/e2guardian.git'
    dest: /usr/src/e2guardian
    version: v5.0

- name: run autogen
  shell: "./autogen.sh"
  args:
    chdir: /usr/src/e2guardian

- name: run configure
  shell: "./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--enable-locallists=yes'"
  args:
    chdir: /usr/src/e2guardian

- name: run make
  shell: "make"
  args:
    chdir: /usr/src/e2guardian

- name: run make install
  shell: "make install"
  args:
    chdir: /usr/src/e2guardian

- name: install service
  shell: "cp /usr/share/e2guardian/scripts/e2guardian.service /lib/systemd/system/ && ln -s /lib/systemd/system/e2guardian.service /etc/systemd/system/e2guardian.service"

- name: enable service
  shell: "systemctl enable e2guardian"

