---

- name: Install package dependencies
  apt: name={{item}} state=installed
  with_items:
    - git
    - build-essential
    - autogen
    - automake
    - base-files
    - base-passwd
    - bash
    - coreutils
    - dash
    - debianutils
    - diffutils
    - dpkg
    - e2fsprogs
    - findutils
    - grep
    - gzip
    - hostname
    - ncurses-base
    - libevent-pthreads-2.0-5
    - libevent-dev
    - ncurses-bin
    - perl-base
    - sed
    - login
    - sysvinit-utils
    - sysvinit
    - tar
    - bsdutils
    - mount
    - util-linux
    - libc6-dev
    - libc-dev
    - gcc
    - g++
    - make
    - dpkg-dev
    - autotools-dev
    - debhelper
    - dh-autoreconf
    - dpatch
    - libclamav-dev
    - libpcre3-dev
    - zlib1g-dev
    - pkg-config
    - libssl-dev
    - libssl1.0.0
    - adduser
    - perl
    - libc6
    - libgcc1
    - libpcre3
    - libtommath0
    - zlib1g
    - clamav
    - clamav-freshclam

- name: check out e2guardian
  git:
    repo: 'https://github.com/e2guardian/e2guardian.git'
    dest: /usr/src/e2guardian
    version: v5.1

- name: run autogen
  shell: "./autogen.sh"
  args:
    chdir: /usr/src/e2guardian

- name: run configure
  shell: "./configure  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/\
var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enabl\
e-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'"
  args:
    chdir: /usr/src/e2guardian

- name: run make
  shell: "make"
  args:
    chdir: /usr/src/e2guardian

- name: run make install
  shell: "make install"
  args:
    chdir: /usr/src/e2guardian

- name: install service
  copy:
    src: /usr/share/e2guardian/scripts/e2guardian.service
    dest: /lib/systemd/system/e2guardian.service
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- file:
    src: /lib/systemd/system/e2guardian.service
    dest: /etc/systemd/system/e2guardian.service
    state: link

#  shell: "cp -f /usr/share/e2guardian/scripts/e2guardian.service /lib/systemd/system/ && ln -s /lib/systemd/system/e2guardian.service /etc/systemd/system/e2guardian.service"

- name: enable service
  shell: "systemctl enable e2guardian"

